server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

  if ($host = www.userbase.com) {
    return 301 https://userbase.com$request_uri;
  }

  if ($host = userbase.dev) {
    return 301 https://userbase.com$request_uri;
  }

  if ($host = www.userbase.dev) {
    return 301 https://userbase.com$request_uri;
  }

  if ($host = userbase.netlify.com) {
    return 301 https://userbase.com$request_uri;
  }

  location = /up {
    add_header Content-Type text/plain;
    return 200 "OK\n";
  }

  location / {
    try_files $uri $uri/ =404;
  }
}
