service: userbase-homepage
image: userbase-homepage

servers:
  web:
    hosts:
      - 127.0.0.1
    options:
      init: true
      stop-timeout: 1

ssh:
  user: deploy
  keys:
    - ~/.ssh/id_ed25519

registry:
  server: 127.0.0.1:5555
  username: dummy
  password: dummy

builder:
  arch: amd64
  local: true
  driver: docker
  context: .

proxy:
  hosts:
    - userbase.com
    - www.userbase.com
    - userbase.dev
    - www.userbase.dev
  app_port: 80
  ssl: false
  forward_headers: true
  healthcheck:
    path: /up
    interval: 1
    timeout: 1

deploy_timeout: 10
drain_timeout: 1
